/*
 * Заказ реcурсов в облаке
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Cloud;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CloudsApi
 */
@Ignore
public class CloudsApiTest {

    private final CloudsApi api = new CloudsApi();

    /**
     * отмена заказа в облаке по id
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void cancelCloudByIdTest() throws Exception {
        String cloudId = null;
        api.cancelCloudById(cloudId);

        // TODO: test validations
    }
    /**
     * Создает заказ в облаке
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCloudTest() throws Exception {
        Cloud response = api.createCloud();

        // TODO: test validations
    }
    /**
     * создание заказа по id облака
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createOrderByIdTest() throws Exception {
        String cloudId = null;
        api.createOrderById(cloudId);

        // TODO: test validations
    }
    /**
     * Метод получение списка ресурсов на облаке
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllCloudsTest() throws Exception {
        Cloud response = api.getAllClouds();

        // TODO: test validations
    }
}
